<?php

/**
 * Copyright (c) Thomas Potaire
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * @category   Teapotio
 * @package    BaseForumBundle
 * @author     Thomas Potaire
 */

namespace Teapotio\Base\ForumBundle\Repository;

use Symfony\Component\Security\Core\User\UserInterface;

use Doctrine\ORM\EntityRepository;

use Doctrine\Common\Collections\ArrayCollection;

/**
 * UserStatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserStatRepository extends EntityRepository
{

    /**
     * Get a UserStat entity from a User
     *
     * @param  UserInterface $user
     *
     * @return UserStat|null
     */
    public function getByUser(UserInterface $user)
    {
        $queryBuilder = $this->createQueryBuilder('us')
                             ->select(array('us'))
                             ->where('us.user = :user_id')->setParameter('user_id', $user->getId());

        $query = $queryBuilder->getQuery();

        try {
            return $query->getSingleResult();
        } catch (\Doctrine\Orm\NoResultException $e) {
            return null;
        }
    }

    /**
     * Get the top users
     *
     * @param   integer  $limit = 10
     *
     * @return  ArrayCollection
     */
    public function getTopUsers($limit = 10)
    {
        $queryBuilder = $this->createQueryBuilder('us')
                             ->select(array('us'))
                             ->orderBy('us.totalMessage', 'desc')
                             ->addOrderBy('us.totalTopic', 'desc')
                             ->setMaxResults($limit);

        $query = $queryBuilder->getQuery();

        return new ArrayCollection($query->getResult());
    }
}
